#!/bin/bash

### Function
connect_wifi () {
mv -f /boot/setup_wifi /usr/local/bin/
chmod +x /usr/local/bin/setup_wifi
/usr/local/bin/setup_wifi  > /dev/null 2>&1
}

remove_wifi () {
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
}

### Create wifi credentials 
sleep 1s
if touch -f /boot/setup_wifi 2>/dev/null; then connect_wifi;
        else remove_wifi > /dev/null 2>&1;
fi

### Clean
systemctl disable credentials
rm -f /usr/local/bin/credentials > /dev/null 2>&1
rm -f /usr/local/bin/setup_wifi > /dev/null 2>&1
