#!/bin/bash
### System Setup Script
echo Running System Setup.
sleep 1s
sudo dpkg-reconfigure locales tzdata keyboard-configuration
echo
echo System is ready to go.
sudo rm -f /usr/local/bin/run-setup
