#!/bin/sh
### BEGIN INIT INFO
# Provides:            Wired internet
# Required-Start:      
# Should-Start:        
# Required-Stop:       
# Should-Stop:         
# Default-Start:       S
# Default-Stop:        0 6
# Short-Description:   Starts and configures eth0 interface.
# Description:         Starts and configures eth0 interface.
### END INIT INFO

# chmod +x /etc/init.d/network
# update-rc.d network defaults S

. /lib/lsb/init-functions

case "${1}" in
   start)
    log_daemon_msg "Ifup eth0"
	interface=eth0
         /sbin/ifup ${interface} &>/dev/null
      ;;

   stop)
    log_daemon_msg "Ifdown eth0"
         interface=eth0
         /sbin/ifdown ${interface} &>/dev/null
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0

# End network
