#!/bin/bash
source kernel.txt
mkdir -p ${TMP3v7}
cd ${TMP3v7}

### Download kernel
echo
echo Downloading kernel.
wget -cq --show-progress https://github.com/raspberrypi/linux/archive/rpi-${VERSION}.tar.gz
echo Done.

### Extract
echo
echo Extracting archive.
tar -xf rpi-${VERSION}.tar.gz
#rm -f rpi-${VERSION}.tar.gz #remove
echo Done.

### Setup
cd ${KERNEL}-${VERSION}
export ARCH=arm
KERNEL=kernel7

### Clean kernel
#make clean
#make mrproper

### Patching
case `grep -Fx "native=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo Applying nc packaging patch.
    patch -p1 < ../${NC}/rpi3b-v7-packaging.patch
    echo Done.
    echo
    ;;
  *)
    #echo
    ;;
esac

case `grep -Fx "crosscompile=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo Applying cc packaging patch.
    patch -p1 < ../${CC}/rpi3b-v7-packaging.patch
    cp -f ../${PAT}/headers-byteshift.patch headers-byteshift.patch
    echo Done.
    echo
    ;;
  *)
    #echo
    ;;
esac

### Foundation defconfig
case `grep -Fx "foundation_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making foundation defconfig.
    make ARCH=arm bcm2709_defconfig &> /dev/null
    echo Done.
    ;;
  *)
    #echo
    ;;
esac

### Builder defconfig
case `grep -Fx "lessfoundation_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making builder defconfig.
    cp -f ../${DEF}/rpi3v7-noinitrd_defconfig arch/arm/configs/
    make ARCH=arm rpi3v7-noinitrd_defconfig &> /dev/null
    echo Done.
    ;;
  *)
    #echo
    ;;
esac

### Custom defconfig
case `grep -Fx "custom_defconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo Making ${MYCONFIG}.
    cp -f ../${DEF}/${MYCONFIG} arch/arm/configs/
    make ARCH=arm ${MYCONFIG} &> /dev/null
    echo Done.
    ;;
  *)
    #echo
    ;;
esac

### Menuconfig
case `grep -Fx "menuconfig=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo Opening menuconfig.
    sleep 1s
    make menuconfig &> /dev/null
    ;;
  *)
    #echo
    ;;
esac

### Build deb
case `grep -Fx "native=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo --- Building deb packages.
    make -j${CORES} ARCH=arm bindeb-pkg
    ;;
  *)
    #echo
    ;;
esac

case `grep -Fx "crosscompile=1" "../../kernel.txt" >/dev/null; echo $?` in
  0)
    echo
    echo --- Building deb packages.
    make -j${CORES} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bindeb-pkg
    ;;
  *)
    #echo
    ;;
esac
echo Done.
echo
