#!/bin/bash
#AARCH64 ROOTFS
source lib/source.txt

FILE=devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz
if ls $FILE &>/dev/null; then exit; 
	else echo "";
fi
wget -cq --show-progress https://github.com/pyavitz/debian-image-builder/releases/download/rootfs/devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz
