#!/bin/bash
#AARCH64 ROOTFS
source lib/source.txt

FILE=devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz
if ls $FILE &>/dev/null; then exit; 
	else echo "";
fi
wget -cq --show-progress https://github.com/pyavitz/rootfs-tarballs/releases/download/devuan/devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz
